//
//  LoginScreen.swift
//  Poker Tracker
//
//  Created by Jonathan Dummett on 21/12/2025.
//

import SwiftUI
import SwiftData

enum currState {
    case login
    case signup
}

func isValidPassword(_ password: String) -> Bool { // Generated by chatgpt
    // At least 8 chars, one uppercase, one number
    let passwordRegex = "^(?=.*[A-Z])(?=.*\\d).{8,}$"
    let passwordTest = NSPredicate(format: "SELF MATCHES %@", passwordRegex)
    return passwordTest.evaluate(with: password)
}

struct LoginScreen: View {
    @Environment(\.modelContext) private var modelContext
    
    @State private var email: String = ""
    @State private var emailValid: Bool = true
    
    @State private var password: String = ""
    @State private var passwordValid: Bool = true
    
    @State private var name: String = ""
    @State private var nameValid: Bool = true
    
    @State private var errorMessage: String = ""
    
    @State private var state: currState = .signup
    @State private var title: String = "Login!"
    @State private var onTap: () -> Void = {}
    @State private var accountPrompt: String = "Don't have an account?"
    @State private var accountButtonLabel: String = "Sign Up!"
    
    var onNavigate: (AppScreen) -> Void
    
    func login() {
    }
    
    func signup() {
        errorMessage = ""
        if email == "" || password == "" || name == "" {
            errorMessage = "All fields must be filled out!"
            return
        }
        if !email.contains("@") || !email.contains(".com") {
            errorMessage = "Invalid email format!"
            return
        }
        if !isValidPassword(password) {
            errorMessage = "Password must be at least 8 characters long, contain one uppercase letter and one number!"
            return
        }
        
        let urlString = "http://127.0.0.1:5000/api/create-verification-code"
        let jsonBody = ["email": email]
        postRequest(to: urlString, jsonBody: jsonBody) { result in
            switch result {
            case .success(let response):
                print("Response: \(response)")
            case .failure(let error):
                print("Error: \(error)")
            }
        }
    }
    
    var body: some View {
        VStack {
            HStack {
                Image(systemName: "chart.xyaxis.line")
                Text("Poker Tracker")
            }
            .font(.title)
            .padding(.bottom, 40)
            .bold(true)
            
            VStack(spacing: 16) {
                /// Input field
                TextField("Email", text: $email)
                    .font(.subheadline)
                    .tint(.orange)
                    .foregroundStyle(.white)
                    .frame(maxWidth: .infinity)
                    .padding(10)
                    .background(Color(red: 0.1, green: 0.1, blue: 0.1))
                    .cornerRadius(8)
                    .autocorrectionDisabled(true)
                    .autocapitalization(.none)
                    .frame(maxWidth: 300)
                
                
                SecureField("Enter Password", text: $password)
                    .textContentType(.password)
                    .autocapitalization(.none)
                    .disableAutocorrection(true)
                    .font(.subheadline)
                    .tint(.orange)
                    .foregroundStyle(.white)
                    .frame(maxWidth: .infinity)
                    .padding(10)
                    .background(Color(red: 0.1, green: 0.1, blue: 0.1))
                    .cornerRadius(8)
                    .frame(maxWidth: 300)
                
                if state == .signup {
                    TextField("Enter Firstname", text: $name)
                        .font(.subheadline)
                        .tint(.orange)
                        .foregroundStyle(.white)
                        .frame(maxWidth: .infinity)
                        .padding(10)
                        .background(Color(red: 0.1, green: 0.1, blue: 0.1))
                        .cornerRadius(8)
                        .autocorrectionDisabled(true)
                        .frame(maxWidth: 300)
                }
                
                /// SimpleButton with fade animation
                if true {
                    SimpleButton(text: title, onTap: onTap)
                        .frame(maxWidth: 300)
                        .opacity(1)
                        .transition(.opacity)
                        .animation(.easeInOut(duration: 0.25), value: title)
                }
                
//                Text("Please only use FAKE emails!")
//                    .font(.caption)
//                    .foregroundColor(.secondary)
            
                /// Error messages
                if !errorMessage.isEmpty {
                    Label {
                        Text(errorMessage)
                            .font(.subheadline)
                            .foregroundColor(.red)
                    } icon: {
                        Image(systemName: "exclamationmark.triangle.fill")
                            .foregroundColor(.red)
                    }
                    .opacity(errorMessage.isEmpty ? 0 : 1)
                    .transition(.opacity)
                    .animation(.easeInOut(duration: 0.25), value: errorMessage)
                }
                /// animation for prompt switch
                if true {
                    HStack(spacing: 4) {
                        Text(accountPrompt)
                            .font(.subheadline)
                        Button(action: { toggleState() }) {
                            Text(accountButtonLabel)
                                .font(.subheadline)
                                .foregroundStyle(Color.orange)
                        }
                    }
                    .opacity(1)
                    .transition(.opacity)
                    .animation(.easeInOut(duration: 0.25), value: accountPrompt)
                }
            }
            SimpleButton(text: "Home Screen TEST BUTTON", onTap: {onNavigate(.homeScreen)})
                .frame(maxWidth: 300)
                .opacity(1)
                .transition(.opacity)
                .animation(.easeInOut(duration: 0.25), value: title)
                .padding(.top, 100)
            Spacer()
        }
        .padding()
        .padding(.top, 100)
        .onAppear { toggleState() }
    }
    
    func toggleState() {
        if state == .login {
            state = .signup
            title = "Sign Up!"
            onTap = signup
            accountPrompt = "Already have an account?"
            accountButtonLabel = "Login!"
        }
        else {
            state = .login
            title = "Login!"
            onTap = login
            accountPrompt = "Don't have an account?"
            accountButtonLabel = "Sign Up!"
        }
    }
}

/// SimpleButton replaces ContinueButton
struct SimpleButton: View {
    var text: String
    var onTap: () -> Void
    
    var body: some View {
        Button(action: onTap) {
            Text(text)
                .foregroundColor(.white)
                .fontWeight(.semibold)
                .frame(maxWidth: .infinity)
                .padding(12)
                .background(Color.orange)
                .cornerRadius(8)
                .shadow(color: Color.white.opacity(0.8), radius: 4, x: 0, y: 0)
        }
        
    }
}

#Preview {
    LoginScreen(onNavigate: { _ in })
}
