//
//  LoginScreen.swift
//  Poker Tracker
//
//  Created by Jonathan Dummett on 21/12/2025.
//

import SwiftUI
import SwiftData

enum currState {
    case login
    case signup
}

struct UserAccountInfo {
    var uuid = UUID()
    var email: String
    var password: String
    var name: String
}

func isValidPassword(_ password: String) -> Bool { // Generated by chatgpt
    // At least 8 chars, one uppercase, one number
    let passwordRegex = "^(?=.*[A-Z])(?=.*\\d).{8,}$"
    let passwordTest = NSPredicate(format: "SELF MATCHES %@", passwordRegex)
    return passwordTest.evaluate(with: password)
}

struct LoginScreen: View {
    @Environment(\.modelContext) private var modelContext
    @EnvironmentObject var appState: AppState
    
    @State private var email: String = ""
    @State private var emailValid: Bool = true
    
    @State private var password: String = ""
    @State private var passwordValid: Bool = true
    
    @State private var name: String = ""
    @State private var nameValid: Bool = true
    
    @State private var errorMessage: String = ""
    
    @State private var state: currState = .signup
    @State private var title: String = "Login!"
    @State private var onTap: () -> Void = {}
    @State private var accountPrompt: String = "Don't have an account?"
    @State private var accountButtonLabel: String = "Sign Up!"
    
    @State private var isLoading: Bool = false
    @State private var verifictionCode: Bool = false
    @State private var codeInput = ""
    
    @State private var savedUserInfo: UserAccountInfo? = nil
    
    var onNavigate: (AppScreen) -> Void
    
    
    var body: some View {
        VStack {
            
            HStack {
                Image(systemName: "chart.xyaxis.line")
                Text("Poker Tracker")
            }
            .font(.title)
            .padding(.bottom, 40)
            .bold(true)
            if !verifictionCode {
                VStack {
                    VStack(spacing: 16) {
                        /// Input field
                        TextField("Email", text: $email)
                            .font(.subheadline)
                            .tint(.orange)
                            .foregroundStyle(.primary)
                            .frame(maxWidth: .infinity)
                            .padding(10)
                            .background(Color(red: 0.9, green: 0.9, blue: 0.9))
                            .cornerRadius(8)
                            .autocorrectionDisabled(true)
                            .autocapitalization(.none)
                            .frame(maxWidth: 300)
                        
                        
                        SecureField("Enter Password", text: $password)
                            .textContentType(.password)
                            .autocapitalization(.none)
                            .disableAutocorrection(true)
                            .font(.subheadline)
                            .tint(.orange)
                            .foregroundStyle(.white)
                            .frame(maxWidth: .infinity)
                            .padding(10)
                            .background(Color(red: 0.9, green: 0.9, blue: 0.9))
                            .cornerRadius(8)
                            .frame(maxWidth: 300)
                        
                        if state == .signup {
                            TextField("Enter Firstname", text: $name)
                                .font(.subheadline)
                                .tint(.orange)
                                .foregroundStyle(.white)
                                .frame(maxWidth: .infinity)
                                .padding(10)
                                .background(Color(red: 0.9, green: 0.9, blue: 0.9))
                                .cornerRadius(8)
                                .autocorrectionDisabled(true)
                                .frame(maxWidth: 300)
                        }
                        
                        /// SimpleButton with fade animation
                        if true {
                            SimpleButton(text: title, onTap: onTap, isLoading: $isLoading)
                                .frame(maxWidth: 300)
                                .opacity(1)
                                .transition(.opacity)
                                .animation(.easeInOut(duration: 0.25), value: title)
                        }
                        
                        //                Text("Please only use FAKE emails!")
                        //                    .font(.caption)
                        //                    .foregroundColor(.secondary)
                        
                        /// Error messages
                        if !errorMessage.isEmpty {
                            Label {
                                Text(errorMessage)
                                    .font(.subheadline)
                                    .foregroundColor(.red)
                            } icon: {
                                Image(systemName: "exclamationmark.triangle.fill")
                                    .foregroundColor(.red)
                            }
                            .opacity(errorMessage.isEmpty ? 0 : 1)
                            .transition(.opacity)
                            .animation(.easeInOut(duration: 0.25), value: errorMessage)
                        }
                        /// animation for prompt switch
                        if true {
                            HStack(spacing: 4) {
                                Text(accountPrompt)
                                    .font(.subheadline)
                                Button(action: { }) {
                                    Text(accountButtonLabel)
                                        .font(.subheadline)
                                        .foregroundStyle(Color.orange)
                                }
                            }
                            .opacity(1)
                            .transition(.opacity)
                            .animation(.easeInOut(duration: 0.25), value: accountPrompt)
                        }
                    }
                    SimpleButton(text: "Home Screen TEST BUTTON", onTap: {onNavigate(.homeScreen)}, isLoading: $isLoading)
                        .frame(maxWidth: 300)
                        .opacity(1)
                        .transition(.opacity)
                        .animation(.easeInOut(duration: 0.25), value: title)
                        .padding(.top, 100)
                    
                    SimpleButton(text: "Verification TEST BUTTON", onTap: {verifictionCode = true}, isLoading: $isLoading)
                        .frame(maxWidth: 300)
                        .opacity(1)
                        .transition(.opacity)
                        .animation(.easeInOut(duration: 0.25), value: title)
                }
            }
            else {
                Text("6 Digit Code")
                    .font(.title)
                Text("A verification code has been sent to your email!")
                    .font(.subheadline)
                
                TextField("Enter code", text: $codeInput)
                    .keyboardType(.numberPad)
                    .onChange(of: codeInput) { oldValue, newValue in
                        // Allow only numbers
                        let filtered = newValue.filter { $0.isNumber }
                        
                        // Limit to 6 digits
                        if filtered.count > 6 {
                            codeInput = String(filtered.prefix(6))
                        } else {
                            codeInput = filtered
                        }
                    }
                    .multilineTextAlignment(.center)
                    .font(.system(size: 24, weight: .semibold, design: .monospaced))
                    .frame(maxWidth: 280)
                    .padding(10)
                    .background(Color(red: 0.1, green: 0.1, blue: 0.1))
                    .cornerRadius(8)
                    .padding(.vertical, 5)
                
                if !errorMessage.isEmpty {
                    Label {
                        Text(errorMessage)
                            .font(.subheadline)
                            .foregroundColor(.red)
                    } icon: {
                        Image(systemName: "exclamationmark.triangle.fill")
                            .foregroundColor(.red)
                    }
                    .opacity(errorMessage.isEmpty ? 0 : 1)
                    .transition(.opacity)
                    .animation(.easeInOut(duration: 0.25), value: errorMessage)
                }
                
                //                SimpleButton(text: "Confirm", onTap: confirm_code, isLoading: $isLoading)
                //                    .frame(maxWidth: 300)
                //                    .opacity(1)
                //                    .transition(.opacity)
                //                    .animation(.easeInOut(duration: 0.25), value: title)
                
            }
            Spacer()
        }
        .padding()
        .padding(.top, 100)
        .onAppear { }
    }
}

struct verification_code_view: View {
    var body: some View {
        VStack {
            
        }
    }
}

/// SimpleButton replaces ContinueButton
struct SimpleButton: View {
    var text: String
    var onTap: () -> Void
    @Binding var isLoading: Bool
    
    var body: some View {
        Button(action: onTap) {
            ZStack {
                if isLoading {
                    ProgressView("")
                        .progressViewStyle(CircularProgressViewStyle())
                        .scaleEffect(1.2)
                        .padding(.top, 15)
                }
                else {
                    Text(text)
                        .foregroundColor(.white)
                        .fontWeight(.semibold)
                }
            }
            .frame(height: 20)
            .frame(maxWidth: .infinity)
            .padding(12)
            .background(Color.orange)
            .cornerRadius(8)
//            .shadow(color: Color.white.opacity(0.8), radius: 4, x: 0, y: 0)
        }
        
    }
}

#Preview {
    LoginScreen(onNavigate: { _ in })
}

